/********************************************************************
* FaddeevaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FaddeevaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFaddeevaDict();
extern void G__cpp_setup_inheritanceFaddeevaDict();
extern void G__cpp_setup_typetableFaddeevaDict();
extern void G__cpp_setup_memvarFaddeevaDict();
extern void G__cpp_setup_globalFaddeevaDict();
extern void G__cpp_setup_memfuncFaddeevaDict();
extern void G__cpp_setup_funcFaddeevaDict();
extern void G__set_cpp_environmentFaddeevaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Faddeeva.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FaddeevaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FaddeevaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FaddeevaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FaddeevaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FaddeevaDictLN_complexlEdoublegR;

/* STUB derived class for protected member access */
