/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBTODHDECAY
#define ROOBTODHDECAY

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#include <vector>
 
class RooBtoDhDecay : public RooAbsPdf {
public:
  RooBtoDhDecay() {} ; 
  RooBtoDhDecay(const char *name, const char *title,
              RooAbsReal& _dt,
	      RooAbsReal& _tau,
	      RooAbsReal& _dm,
	      RooAbsReal& _sin2beta,
	      RooAbsReal& _cos2beta,
	      RooAbsReal& _K,
	      RooAbsReal& _Kb,
	      RooAbsReal& _C,
	      RooAbsReal& _S,
	      RooAbsReal& _moment,
	      RooAbsReal& _parity);
  RooBtoDhDecay(const RooBtoDhDecay& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBtoDhDecay(*this,newname); }
  inline virtual ~RooBtoDhDecay() { }

protected:
  RooRealProxy dt;
  RooRealProxy tau;
  RooRealProxy dm;
  RooRealProxy sin2beta;
  RooRealProxy cos2beta;
  RooRealProxy K;
  RooRealProxy Kb;
  RooRealProxy C;
  RooRealProxy S;
  RooRealProxy moment;
  RooRealProxy parity;
  
  Double_t evaluate() const ;

private:
  ClassDef(RooBtoDhDecay,1) // Your description goes here...
};
 
#endif
