/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBTODHFADEEVA
#define ROOBTODHFADEEVA

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#include <complex>
#include "Faddeeva.hh"

#include <vector>

class RooBtoDhFadeeva : public RooAbsPdf {
public:
  RooBtoDhFadeeva() {}
  RooBtoDhFadeeva(const char *name, const char *title,
          RooAbsReal& _dt,
	      RooAbsReal& _tau,
	      RooAbsReal& _dm,
	      RooAbsReal& _sin2beta,
	      RooAbsReal& _cos2beta,
	      RooAbsReal& _K,
	      RooAbsReal& _Kb,
	      RooAbsReal& _C,
	      RooAbsReal& _S,
	      RooAbsReal& _moment,
          RooAbsReal& _parity,
          RooAbsReal& _sigma);
  RooBtoDhFadeeva(const RooBtoDhFadeeva& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBtoDhFadeeva(*this,newname); }
//  inline virtual ~RooBtoDhFadeeva() {}

protected:
  RooRealProxy dt;
  RooRealProxy tau;
  RooRealProxy dm;
  RooRealProxy sin2beta;
  RooRealProxy cos2beta;
  RooRealProxy K;
  RooRealProxy Kb;
  RooRealProxy C;
  RooRealProxy S;
  RooRealProxy moment;
  RooRealProxy parity;
  RooRealProxy sigma;

  Double_t evaluate() const ;

private:
//  ClassDef(RooBtoDhFadeeva,1) // Your description goes here...
};
 
#endif
