/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCOMBPDF
#define ROOCOMBPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#include "RooChebychev.h"
#include "RooFormula.h"
#include "RooArgusBG.h"
#include "RooGaussian"
#include "RooAddPdf.h"
#include "RooRealVar.h"
#include "RooFormulaVar.h"
#include "RooProdPdf.h"
#include "RooArgSet.h"
 
class RooCombPdf : public RooAbsPdf {
public:
  RooCombPdf() {} ; 
  RooCombPdf(const char *name, const char *title,
	      RooAbsReal& _de,
	      RooAbsReal& _mbc,
	      RooAbsReal& _c10,
	      RooAbsReal& _c11,
	      RooAbsReal& _c20,
	      RooAbsReal& _c21,
          RooAbsReal& _c3,
          RooAbsReal& _c4,
	      RooAbsReal& _edge,
	      RooAbsReal& _parqq,
	      RooAbsReal& _fg,
	      RooAbsReal& _mbc0,
	      RooAbsReal& _width,
	      RooAbsReal& _parbb,
	      RooAbsReal& _fbb);
  RooCombPdf(const RooCombPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCombPdf(*this,newname); }
  inline virtual ~RooCombPdf() { }

protected:

  RooRealProxy de ;
  RooRealProxy mbc ;
  RooRealProxy c10 ;
  RooRealProxy c11 ;
  RooRealProxy c20 ;
  RooRealProxy c21 ;
  RooRealProxy c3 ;
  RooRealProxy c4 ;
  RooRealProxy edge ;
  RooRealProxy parqq ;
  RooRealProxy fg ;
  RooRealProxy mbc0 ;
  RooRealProxy width ;
  RooRealProxy parbb ;
  RooRealProxy fbb ;
  
  Double_t evaluate() const ;

private:
  RooGaussian* g;
  RooArgusBG* argus_bb;
  RooChebychev* cheb_bb;
  RooArgusBG* argus_qq;
  RooChebychev* cheb_qq;
  RooFormulaVar* c1;
  RooFormulaVar* c2;
  RooAddPdf* pdf;
  RooProdPdf* pdf_bb;
  RooProdPdf* pdf_qq;
  RooAddPdf* pdf;

// ClassDef(RooCombPdf,1) // Your description goes here...
};
 
#endif
