/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMESIG1STORDER
#define ROOTIMESIG1STORDER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#include <vector>
 
class RooBtoDhDecay : public RooAbsPdf {
public:
  RooBtoDhDecay() {} ; 
  RooBtoDhDecay(const char *name, const char *title,
              RooAbsReal& _dt,
	      RooAbsReal& _tau,
	      RooAbsReal& _dm,
	      RooAbsReal& _K,
	      RooAbsReal& _Kb,
	      RooAbsReal& _C,
	      RooAbsReal& _S,
	      RooCategory& _moment,
	      RooCategory& _parity);
  RooBtoDhDecay(const RooBtoDhDecay& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBtoDhDecay(*this,newname); }
  inline virtual ~RooBtoDhDecay() { }

protected:
  RooAbsRealProxy dt;
  RooAbsRealProxy tau;
  RooAbsRealProxy dm;
  RooAbsRealProxy K;
  RooAbsRealProxy Kb;
  RooAbsRealProxy C;
  RooAbsRealProxy S;
  RooCategoryProxy moment;
  RooCategoryProxy parity;
  
  Double_t evaluate() const ;

private:
  vector<double> C,S;
  ClassDef(RooBtoDhDecay,1) // Your description goes here...
};
 
#endif
